version: '1'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start"]
    ports:
      - 3000
    env_file:
      - .env
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "test"]
    env_file:
      - .env.test
    environment:
      - NODE_ENV=test
