version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start"]
    ports:
      - 3000
    env_file:
      - .env
  redis:
    image: redis:4.0.9
    command: redis-server --requirepass VMware123!
    ports:
      - "6379:6379"